---
title: "Belonging in STEM survey tidysesh"
author: "JP Flores"
date: "5/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load the packages 
```{r}
library(tidyverse)
library(readxl)
library(janitor)
library(plotly)
```

Import the data
```{r}
bestem_data <-read_csv("/Users/jpflores/Desktop/Desktop - JP’s MacBook Pro/bestem/data through 5_30.xlsx - anonymizing the data.csv")

View(bestem_data)

bestem_data <- bestem_data %>% 
  select(- `Row # from Qualtrics`,
         - ResponseId,- X15, - X16, - X17, - X27, - X28, - X29, - X39, - X40,
         - X41, - X51, - X52, - X53, - X63, - X64, - X65, - X75, - X76, - X77, - X87, - X88, - X89,
         - X99, - X100, - X101, - X111, - X112, - X113, - X123, - X124, - X125, - X135, - X136,
         - X137, - X147, - X148, - X149, - X159, - X160, - X161, - X171, - X172, - X173, - X183,
         - X184, - X185, - X195, - X196, - X197, - X207, - X208, - X209, - X219, - X220,
         - X221, - X231, - X232, - X233, - X243, - X244, - X245, - X255, - X256, - X257,- X267,
         - X268, - X269, - X279, - X280, - X281, - X291, - X292, - X293, - X303, -X304, - X305,
         - X315, - X316, - X317, - X327, - X328, - X329, - X339, - X340, - X341, - X351, - X352,
         - X353, - X363, - X364, - X365, - X375, - X376, - X377, - X387, - X388, - X389, - X399,
         - X400, - X401, - X411, - X412, - X413, - X423, - X424, - X438, - X440, - X441, - X442, - X443, 
         - X444, - X445, - X447, - X448
         )

bestem_data <- bestem_data[-c(1:2) , ]
```

Export for Sherman and Levitan for further direction on how to organize the data 
```{r}
# write_csv(bestem_data, "bestem_data.csv")
```


